"""Initial migration

Revision ID: 067ed2021d18
Revises: 
Create Date: 2025-09-08 22:12:28.745825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '067ed2021d18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('profile_image_url', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('settings', backend.mini_webui.internal.db.JSONField(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_active_at', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('email')
    )
    op.create_table('chat',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('chat', backend.mini_webui.internal.db.JSONField(), nullable=False),
    sa.Column('meta', backend.mini_webui.internal.db.JSONField(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=True),
    sa.Column('share_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_id')
    )
    op.create_index('updated_at_idx', 'chat', ['updated_at'], unique=False)
    op.create_index('user_id_archived_idx', 'chat', ['user_id', 'archived'], unique=False)
    op.create_index('user_id_idx', 'chat', ['user_id'], unique=False)
    op.create_index('user_id_pinned_idx', 'chat', ['user_id', 'pinned'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('data', backend.mini_webui.internal.db.JSONField(), nullable=True),
    sa.Column('meta', backend.mini_webui.internal.db.JSONField(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('chat_id_created_at_idx', 'message', ['chat_id', 'created_at'], unique=False)
    op.create_index('chat_id_idx', 'message', ['chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('chat_id_idx', table_name='message')
    op.drop_index('chat_id_created_at_idx', table_name='message')
    op.drop_table('message')
    op.drop_index('user_id_pinned_idx', table_name='chat')
    op.drop_index('user_id_idx', table_name='chat')
    op.drop_index('user_id_archived_idx', table_name='chat')
    op.drop_index('updated_at_idx', table_name='chat')
    op.drop_table('chat')
    op.drop_table('user')
    op.drop_table('setting')
    # ### end Alembic commands ###